apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test
  namespace: default
  annotations:
    autoscaling.knative.dev/min-scale: "1"
spec:
  template:
    spec:
      containers:
      - image: docker.io/chzhyang/tensorflow-image-recognition:latest